// การ์ดฝึก "บอกชื่อกระบวนการ" (รูปจากข้อสอบที่ไม่มีลายมือ + คำใบ้จากข้อสอบเติมคำ)
export const flashcards = [
  // ---- Sheet metal (รูป) ----
  { topic: 'sheet-metal', fig: 'f62-p04-00', q: 'ซ้ายและขวาคือกระบวนการอะไร (ลูกศรเขียวชี้ final product)', a: 'ซ้าย Punching (Piercing) · ขวา Blanking', hint: 'ดูว่าเก็บชิ้นไหนไว้ใช้' },
  { topic: 'sheet-metal', fig: 'f62-p04-01', q: 'กระบวนการอะไร', a: 'Shearing', hint: 'มีระยะ c ระหว่างคม' },
  { topic: 'sheet-metal', fig: 'f62-p04-02', q: 'กระบวนการอะไร', a: 'Roll bending', hint: 'ลูกกลิ้งสามลูก' },
  { topic: 'sheet-metal', fig: 'f62-p04-04', q: 'กระบวนการอะไร', a: 'Stretch forming', hint: 'ดึงตึงแล้วพันรอบแม่พิมพ์' },
  { topic: 'sheet-metal', fig: 'f62-p04-06', q: 'กระบวนการอะไร', a: 'Edge bending (Wipe die)', hint: 'มี pressure pad' },
  { topic: 'sheet-metal', fig: 'f62-p04-07', q: 'กระบวนการอะไร (คล้ายงานกลึง)', a: 'Spinning' },
  { topic: 'sheet-metal', fig: 'f62-p04-09', q: 'กระบวนการอะไร', a: 'Ironing', hint: 'ผนังถ้วยบางลง' },
  { topic: 'sheet-metal', fig: 'f62-p04-10', q: 'กระบวนการอะไร (กล่องปลั๊กไฟ)', a: 'Progressive blanking and punching die' },
  { topic: 'sheet-metal', fig: 'f62-p04-11', q: '(1), (2) และ C คืออะไร', a: '(1) Punch · (2) Die · C Clearance' },
  { topic: 'sheet-metal', fig: 'f62-p05-01', q: 'ชิ้น Body side outer ของรถยนต์ ใช้กระบวนการอะไร', a: 'Tailor welded blank' },
  { topic: 'sheet-metal', fig: 'f62-p05-02', q: 'กระบวนการอะไร', a: 'Perforating', hint: 'รูจำนวนมากในครั้งเดียว' },
  { topic: 'sheet-metal', fig: 'f62-p05-03', q: '(A) และ (B) คือกระบวนการอะไร', a: '(A) Nibbling · (B) Notching', hint: 'โค้งยาว vs บากขอบ' },
  { topic: 'sheet-metal', fig: 'sm63-p04-02', q: 'แกนหม้อแปลง ใช้กระบวนการโลหะแผ่นอะไรบ้าง (5 ชื่อ)', a: 'Slitting, Shearing, Blanking, Piercing, Notching' },
  { topic: 'sheet-metal', q: 'ผลิต H-Beam, C-channel, Tee-bar แขวนฝ้าเพดาน ด้วยลูกกลิ้งหลายสถานี', a: 'Roll forming' },
  { topic: 'sheet-metal', q: 'ทดสอบ formability ด้วยวิธีอะไร', a: 'Cupping test (Swift หรือ Erichsen)' },
  { topic: 'sheet-metal', q: 'เครื่องมือวัดความหนาแผ่นโลหะ', a: 'SWG และ US Standard Thickness Gauge' },
  { topic: 'sheet-metal', q: 'แผ่นคลี่ของข้อต่อสี่เหลี่ยมเป็นกลม ใช้วิธีอะไร', a: 'Triangulation' },
  { topic: 'sheet-metal', q: 'แผ่นคลี่ของกรวย ใช้วิธีอะไร', a: 'Radial line development' },
  { topic: 'sheet-metal', q: 'แผ่นคลี่ของท่อกลมตัดเฉียง ใช้วิธีอะไร', a: 'Parallel line development' },
  { topic: 'sheet-metal', q: 'ตัดแนวตรงยาวไม่มีเศษ เช่น ผ่าม้วนเหล็กเป็นแถบแคบ', a: 'Slitting' },
  { topic: 'sheet-metal', q: 'ตัดบางส่วนโดยไม่มีเนื้อหลุด แล้วพับลิ้นขึ้น', a: 'Lancing' },
  { topic: 'sheet-metal', q: 'เฉือนขอบออกนิดเดียวให้เรียบและแม่น', a: 'Shaving' },
  // ---- Welding (คำใบ้) ----
  { topic: 'welding', q: 'อาร์ก + อิเล็กโทรดไม่สิ้นเปลือง', a: 'GTAW (และ PAW)' },
  { topic: 'welding', q: 'ความต้านทานไฟฟ้า + รอยต่อเกย', a: 'RSW (Resistance Spot Welding)' },
  { topic: 'welding', q: 'เชื่อมรางรถไฟ ไม่ใช้ไฟฟ้า หลักการคล้ายหล่อโลหะ', a: 'Thermit welding (TW)' },
  { topic: 'welding', q: 'ก๊าซปกคลุม CO₂ ผสมอาร์กอน', a: 'GMAW (MAG)' },
  { topic: 'welding', q: 'ลวด ER70S-6', a: 'GMAW' },
  { topic: 'welding', q: 'ลวด E7016 / E6013', a: 'SMAW' },
  { topic: 'welding', q: 'แหล่งจ่ายของ SMAW', a: 'CC (กระแสคงที่)' },
  { topic: 'welding', q: 'GTAW เชื่อมอะลูมิเนียม ใช้อิเล็กโทรดอะไร', a: 'ทังสเตนบริสุทธิ์ EWP (เขียว) ไฟ AC' },
  { topic: 'welding', q: 'Fastener ใหญ่ ชิ้นงานหนา โครงสร้างอาคาร', a: 'Stud arc welding' },
  { topic: 'welding', q: 'ตะแกรงลวดรถเข็น และน็อตตัวเมียกับโครงรถ', a: 'RPW (Projection)' },
  { topic: 'welding', q: 'วาล์วไอดีไอเสียรถยนต์', a: 'Friction welding (FRW)' },
  { topic: 'welding', q: 'ท่อมีตะเข็บจากแผ่นเหล็ก อัตโนมัติ ไม่เติมลวด', a: 'HFRW' },
  { topic: 'welding', q: 'มองไม่เห็นบ่อหลอม อาร์กอยู่ใต้ฟลักซ์', a: 'SAW' },
  { topic: 'welding', q: 'ถังน้ำมัน รอยต่อต่อเนื่องกันรั่ว ใช้อิเล็กโทรดล้อหมุน', a: 'RSEW (Seam)' },
  { topic: 'welding', q: 'ยิงอิเล็กตรอนในสุญญากาศ เกิดรังสีเอ็กซ์', a: 'EBW (Electron beam)' },
  { topic: 'welding', q: 'ตัดความร้อนที่ตัดอะลูมิเนียม/สเตนเลสได้', a: 'Plasma arc cutting' },
  { topic: 'welding', q: 'ตัดความร้อนที่ตัดอะลูมิเนียมไม่ได้', a: 'Oxy-fuel (oxyacetylene) cutting' },
  { topic: 'welding', q: 'เชื่อมเหล็กกล้าละมุนด้วย OAW ใช้เปลวอะไร', a: 'Neutral flame (1:1)' },
  { topic: 'welding', q: 'ตัดด้วย Oxyacetylene ตามสไลด์ใช้เปลวอะไร', a: 'Oxidizing flame (1.5:1)' },
  { topic: 'welding', q: 'สีถัง O₂ / CO₂ / C₂H₂ / Ar', a: 'ดำ / ดำไหล่ขาว / แดงเลือดหมู / ฟ้าหม่น' },
  { topic: 'welding', q: 'ตรวจรอยแตกภายใน เข้าถึงได้ด้านเดียว', a: 'UT (Ultrasonic testing)' },
  { topic: 'welding', q: 'ตรวจผิว เฉพาะวัสดุเฟอร์โรแมกเนติก', a: 'MT (Magnetic particle)' },
  { topic: 'welding', q: 'รอยบกพร่องที่ร้ายแรงที่สุด', a: 'Crack (รอยแตก)' },
  { topic: 'welding', q: 'ร่องที่ขอบรอยเชื่อม (toe) ถูกหลอมแล้วไม่เติม', a: 'Undercut' },
];
